/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.1_2 */
public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTSTATICIMPORT = 2;
  public int JJTNONSTATICIMPORT = 3;
  public int JJTMETHOD = 4;
  public int JJTPARAMLIST = 5;
  public int JJTRETURN = 6;
  public int JJTCLASS = 7;
  public int JJTEXTENDS = 8;
  public int JJTVARDECLARATION = 9;
  public int JJTBODY = 10;
  public int JJTTYPE = 11;
  public int JJTIDENTIFIER = 12;
  public int JJTCONDITION = 13;
  public int JJTASSIGN = 14;
  public int JJTWHILE = 15;
  public int JJTIFSTATEMENT = 16;
  public int JJTSCOPE = 17;
  public int JJTLENGTH = 18;
  public int JJTARRAY = 19;
  public int JJTMETHODINVOCATION = 20;
  public int JJTARGLIST = 21;
  public int JJTAND = 22;
  public int JJTLESS = 23;
  public int JJTADD = 24;
  public int JJTSUB = 25;
  public int JJTMUL = 26;
  public int JJTDIV = 27;
  public int JJTINTEGER = 28;
  public int JJTBOOLEAN = 29;
  public int JJTTHIS = 30;
  public int JJTNEWINTARRAY = 31;
  public int JJTNEWOBJECT = 32;
  public int JJTNOT = 33;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "StaticImport",
    "NonStaticImport",
    "Method",
    "ParamList",
    "Return",
    "Class",
    "Extends",
    "VarDeclaration",
    "Body",
    "Type",
    "Identifier",
    "Condition",
    "Assign",
    "While",
    "IfStatement",
    "Scope",
    "Length",
    "Array",
    "MethodInvocation",
    "ArgList",
    "And",
    "Less",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Integer",
    "Boolean",
    "This",
    "NewIntArray",
    "NewObject",
    "Not",
  };
}
/* JavaCC - OriginalChecksum=e954a80a9850bf24194daf17c23c13f8 (do not edit this line) */
